[package]
name = "foreman"
version = "0.0.1"
authors = ["Mike Bush <mike@survemobility.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
futures = { version = "0.3.15", features = ["executor"] }
