[package]
name = "chief"
version = "0.0.1"
authors = ["Mike Bush <mike@survemobility.com>"]
edition = "2018"

[dependencies]
crossbeam-channel = "0.5.1"

[dev-dependencies]
futures = { version = "0.3.15", features = ["executor"] }
